### PR TITLE
EBMEDS-1614 EBMEDS browser support

### PR DESCRIPTION
**Pull request by dnikomon**
Related to this [ticket](https://jira.duodecim.fi/browse/EBMEDS-1614)

Description: 
We need to document this to our material we send to customers so they can prepare upgrade to ebmeds 2.0. Or in case of a new customer, the same applies.

Why?
This is part of the rollout material that is sent to customers. 

Comments?

### CODE REVIEW

**Comment by jouko-kelomaki-solita** [comment]
It would be rad, if this was automatically generated from the output of the package.json. Unfortunately probably quite far off the scope of this ticket. Perhaps write a new ticket about it though?

**Comment by mikaelpaj** [comment]
Probably rather hard to automate and make it readable. It's also not like these change that often if the documentation doesn't mention exact versions.

**Comment by joonatanv** [comment]
Yeah, wouldn't stress it if there isn't an easy solution / package for it.

**Comment by joonatanv** [comment]
This should be updated to contain Edge as well. I think that Safari isn't something we need to support from the get-go.

**Review by joonatanv — APPROVED** [review]

**Review by SkylarPhx — APPROVED** [review]

**Pull request merged**
